config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/scans/new', to: 'scans#new', as: 'scans_new'
  resources :additives, only: [:index, :show]
  resources :allergens, only: [:index, :show]

  resources :scans, only: [:new, :create, :show, :destroy] do
    post :capture, on: :collection
    delete :delete, on: :member # Add a custom route for deleting images
  end
end

app/models/additive.rb
class Additive < ApplicationRecord
  has_many :ingredients
  has_many :allergens

  validates :name, presence: true
  # validates :name, uniqueness: true


  include PgSearch::Model
  pg_search_scope :search_by_aa,
                  against: %i[name],
                  associated_against: { allergens: [:name] },
                  using: { tsearch: { prefix: true } }

end

app/models/allergen.rb
class Allergen < ApplicationRecord
  has_many :ingredients
  has_many :additives

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :additive
  belongs_to :allergen
end

app/models/scan.rb
class Scan < ApplicationRecord
  has_one_attached :image_url
end

app/controllers/additives_controller.rb
class AdditivesController < ApplicationController

  def index
    @additives = Additive.all.order(:name)
    @allergens = Allergen.all.order(:name)



    if params[:query].present?
      @additives = @additives.where('name ILIKE ?', "%#{params[:query]}%")
    end
    # @additives = @additives.search_by_aa(params[:query]) if params[:query].present?
    respond_to do |format|
      format.html
      format.text { render partial: "result", locals: { additives: @additives }, formats: [:html] }
    end
  end
end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  require 'google/cloud/vision'
  require_relative '../../services/google_vision'

  def index
  end

  def new
    @scan = Scan.new
    render :new
  end

  def create
    @scan = Scan.new(image_params)

    if @scan.save
      flash[:notice] = "Scan created successfully"
      redirect_to scan_path(@scan)
    else
      render json: { text: "Error creating scan" }, status: :unprocessable_entity
    end
  end

  def destroy
    @scan = Scan.find(params[:id])
    if @scan.created_at <= 1.hour.ago
      Cloudinary::Uploader.destroy(@scan.image_public_id)
    end
  end


  def show
    @scan = Scan.find(params[:id])
    @image_url = "https://res.cloudinary.com/dvqsmda6p/image/upload/v1698067820/development/#{@scan.image_url.key}"

    if @image_url.present?
      # consider running text extraction and saving the extracted text in database item, so you don't have to call the API everytime the page is refreshed
      google_vision_service = GoogleVisionService.new(@image_url)
      @extracted_text = google_vision_service.extract_text

      respond_to do |format|
        format.json do
          render json: { scan: @scan, extracted_text: @extracted_text }
        end
        format.html
      end

      # @additives = Additive.all
      # @additive_words = @extracted_text.gsub("\n", "").split(/\s+|、/)
      # @matching_additives = Additive.select { |additive| @extracted_text.include?(additive.name) || (@extracted_text.include?(additive.display_name) unless additive.display_name.nil?)}
      @matching_additives = Additive.select { |additive| additive.searchable_names.any? { |name| @extracted_text.gsub(/\s+/, "").include?(name) } }
      # @matching_additives = Additive.select { |additive| @extracted_text.include?(additive.display_name || additive.name)}

      # @additive_words.each do |word|
      #   @matching_additives.concat(@additives.select { |additive| word.include?(additive.name || additive.display_name) })
      # end

      @allergens = Allergen.all
      @allergen_words = @extracted_text.gsub("\n", "").split(/\s+|、/)
      @matching_allergens = []

      @allergen_words.each do |word|
        @matching_allergens.concat(@allergens.select { |allergen| word.include?(allergen.name) })
      end

    else
      @error_message = "Image URL is missing."
      respond_to do |format|
        format.json do
          render json: { scan: @scan, error: @error_message }, status: :unprocessable_entity
        end
        format.html
      end
    end
  end

 private

 def image_params
  params.require(:scan).permit(:image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/additives/_instraction.html.erb
<div style="text-align: center;">
  <div style="text-align: center; margin-top: 20px; background-color: #EFA30E; color: white;">
    <h1>〜使い方〜</h1>
  </div>

  <div style="text-align: left; margin-top: 20px;">
    <h1>・添加物の検索</h1>
    <img src="<%= asset_path('how_to_1.png') %>" alt="pic" width="480px" height="400px">

    <h1>・スキャンで添加物・アレルギーを読み取る</h1>
    <img src="<%= asset_path('how_to_2.png') %>" alt="pic" width="480px" height="400px">
  </div>

  <a href="/additives">
    <button type="button" class="btn start" style="width: 120px; height: 32px; margin-top: 20px; background-color: #EFA30E; color: white;">スタート</button>
  </a>
</div>

app/views/additives/_instruction.html.erb
<div style="text-align: center;">
  <div style="text-align: center; margin-top: 20px; background-color: #EFA30E; color: white;">
    <h1>〜使い方〜</h1>
  </div>
  <div class="left-tab-content" style="text-align: left; margin-top: 20px;">
    <h1 class="explanation-bullet">・添加物の検索</h1>
    <img src="<%= asset_path('how_to_1.png') %>" alt="pic" width="480px" height="400px" class="explanation-pic">
    <h1 class="explanation-bullet">・スキャンで添加物・アレルギーを読み取る</h1>
    <img src="<%= asset_path('how_to_2.png') %>" alt="pic" width="480px" height="400px" class="explanation-pic">
  </div>
  <a href="/additives">
    <button type="button" class="btn start" style="width: 120px; height: 32px; margin: 24px 0 32px 0; background-color: #EFA30E; color: white;">スタート</button>
  </a>
</div>

app/views/additives/_result.html.erb
<div id="emptySearchImage" class="text-center">
  <%# Replace URL for Image here ↓ %>
  <img src="<%= asset_path('question.png') %>" class="girl" alt="search_icon">
</div>
<div class="results-list" data-refresh-list-target="result">
  <% if params[:query].present? %>
    <% (@additives + @allergens).each do |item| %>
      <% if item.name.downcase.include?(params[:query].downcase) %>
        <div class="card card-trip search_results mb-3 od py-1 px-2" data-controller="enty-thinner" data-action="click->enty-thinner#dropdown">
          <div class="p-3">
            <div class="overflow-container" data-enty-thinner-target="text">
              <%# Arrow symbol is here %>
              <p class="pt-2 mb-0 fs-5"> <% if @additives.include?(item) && [item.information, item.purpose, item.url].any?(&:present?) || @allergens.include?(item) && item.icon.present? %>
                  <i class="fa-solid fa-caret-down"></i>
                <% end %> Name: <%= item.name.capitalize %> </p>
            </div>
          </div>
          <div class="justify-content-center p-3 d-none" data-enty-thinner-target="details">
            <div class="justify-content-center p-3">
              <% if item.information.present? %>
                <p class="pt-2 mb-2 fs-5"> Information: <%= item.information %></p>
              <% end %>
              <% if @additives.include?(item) && item.purpose.present? %>
                <p class="pt-2 mb-0 fs-5">Purpose: <%= item.purpose %></p>
              <% end %>
              <% if @additives.include?(item) && item.url.present? %>
                Reference URL: <a href="<%= item.url %>" target="_blank"><%= item.url %></a>
              <% end %>
              <div class="icon">
                <% if @allergens.include?(item) && item.icon.present? %>
                  <%= image_tag item.icon, class: "icon-smaller" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/additives/_search.html.erb
<div class="row justify-content-center">
  <div class="my-3 ml-3">
    <div data-controller="refresh-list">
      <%= form_with url: additives_path, method: :get, html: { class: "d-flex justify-content-center", data: { refresh_list_target: 'form' } } do |f| %>
        <div class="d-flex align-items-center">
          <div class="col-16">
            <%= f.text_field :query,
                     class: "form-control",
                     placeholder: 'キーワードを入力' ,
                     value: params[:query],
                     data: {
                      refresh_list_target: 'searchInput',
                      action: "keyup->refresh-list#update"
                    } %>
          </div>
        </div>
      <% end %>
      <%= render 'result', additives: @additives %>
    </div>
  </div>
</div>

app/views/additives/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <%= render "pages/top_navbar" %>
    <%= render "pages/navbar" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SafeEats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon2.png' %>
  </head>
  <body style="position: relative;">
    <div style="background-color: white;">
      <div class="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/_navbar.html.erb
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
    <%= render "additives/instruction" %>
  </div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
    <%= render "additives/search", additives: @additive %>
  </div>
</div>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="false"> <i class="fa-solid fa-question"></i> 使い方</button>
    <button class="nav-link yellow-circular-tab upper-half" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false" onclick="window.location.href='<%= scans_new_path %>'">
      <span><i class="fa-solid fa-camera fa-xl" style="color: #000000;"></i></span>
    </button>
    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false"> <i class="fa-solid fa-magnifying-glass"></i> 検索</button>
  </div>
</nav>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    // instruction のページを非表示にする
    document.getElementById("nav-home").classList.remove("show", "active");
    // ボタンをアクティブでない状態にする
    document.getElementById("nav-home-tab").classList.remove("active");
  });
</script>

app/views/pages/_top_navbar.html.erb
  <nav class="navbar navbar-expand-lg ">
  <div class="container-fluid justify-content-center">
    <%= image_tag("favicon2.png", alt: "Logo Image", width: "30", height: "24", class: "d-inline-block align-text-top") %>
    Safe Eats
  </div>
</nav>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1, user-scalable=no">
    <title>Document</title>
    <style>
      /* カーソルインディケーターのスタイル変更 */
      #carouselExampleIndicators .carousel-indicators button {
        background-color: grey; /* インディケーターの色を変更 */
        border-color: white; /* ボーダーの色を変更 */
        height: 5px; /* インディケーターの高さを指定 */
        width: 30px; /* インディケーターの幅を指定 */
      }
      /* アクティブなカーソルインディケーターのスタイル変更 */
      #carouselExampleIndicators .carousel-indicators button.active {
        background-color: #5BB998; /* アクティブなインディケーターの色を変更 */
        border-color: white; /* アクティブなインディケーターのボーダーの色を変更 */
      }
    </style>
  </head>
  <body>
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner d-flex align-items-center">
        <div class="carousel-item active">
          <img src="<%= asset_path('search.png') %>" class="d-block carousel-image" alt="search_icon">
          <div class="title1">
            <h1>添加物をすぐにチェック</h1>
            <p>商品の原材料名をスキャンして、含まれている添加物をすぐに調べることができます</p>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <a href="/additives">
              <button type="button" class="btn btn-outline-success" style="width: 120px; height: 32px;">スキップ</button>
            </a>
            <br>
            <br>
          </div>
        </div>
        <div class="carousel-item">
          <img src="<%= asset_path('allergy.png') %>" class="d-block carousel-image" alt="additives">
          <div class="title2">
            <h1>アレルギーもすぐにチェック</h1>
            <p>同時に含まれているアレルギーもチェックできます<br>
              <br>
            </p>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <a href="/additives">
              <button type="button" class="btn btn-outline-success" style="width: 120px; height: 32px;">スキップ</button>
            </a>
            <br>
            <br>
          </div>
        </div>
        <div class="carousel-item">
          <img src="<%= asset_path('check.png') %>" class="d-block carousel-image" alt="check">
          <div class="title3">
            <h1>どこでも使える食品判断ツール</h1>
            <p>外出先でもアプリを使って含まれる添加物やアレルギーを<br>
              確認し、より安全な食生活を送るツールとして使っていただけます。</p>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <a href="/additives">
              <button type="button" class="btn btn-outline-success" style="width: 120px; height: 32px;">スタート</button>
            </a>
            <br>
            <br>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev" style="red">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next w-80" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" style="" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </body>
</html>
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Index", scans_path %>
<%# ここから下はlanding page %>

app/views/pages/landing_page.html.erb
<!DOCTYPE html>
<html>
<h1>Welcome to Safe eats App</h1>

<%= link_to 'Start', root_path, class: 'start-button' %>



</html>

app/views/scans/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Take a Picture</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <div class="container me-3 my-3">
      <h1>ラベルを読み取る</h1>
      <video id="camera-feed" autoplay></video>
      <!-- Loading screen -->
      <div class="loading-screen hidden" id="loadingScreen">
        <div class="spinner"></div>
        <p>読み込み中...</p>
      </div>
      <%= simple_form_for @scan, url: '/scans', html: { multipart: true, id: 'capture-form' } do |f| %>
        <%= f.input :image_url, as: :file, input_html: { id: 'file-input' } %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <button id="capture-button" class="btn btn-primary">撮影してアップロード</button>
        <button id="upload-button" class="btn btn-primary">ファイルをアップロード</button>
      <% end %>
    </div>
    <script>
      // Function to access the camera and display the video feed
      function setupCamera() {
        navigator.mediaDevices.getUserMedia({ video: true })
          .then(function (stream) {
            var video = document.getElementById('camera-feed');
            video.srcObject = stream;
          })
          .catch(function (error) {
            console.error('Error accessing the camera:', error);
          });
      }

      // Call the setupCamera function when the page loads
      window.addEventListener('load', setupCamera);

      // Button click event handler to capture and upload the image
      document.getElementById('capture-button').addEventListener('click', function () {
        // Show the loading screen
        document.getElementById('loadingScreen').classList.remove('hidden');
      });

      // Button click event handler to upload the file
      document.getElementById('upload-button').addEventListener('click', function (e) {
        e.preventDefault();

        // Show the loading screen
        document.getElementById('loadingScreen').classList.remove('hidden');

        // Submit the form
        document.getElementById('capture-form').submit();
      });

      // Button click event handler to capture and upload the image
      document.getElementById('capture-form').addEventListener('submit', function (e) {
        e.preventDefault();

        // Capture a frame from the camera and save it as a Blob
        var video = document.getElementById('camera-feed');
        var canvas = document.createElement('canvas');
        var context = canvas.getContext('2d');

        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        context.drawImage(video, 0, 0, canvas.width, canvas.height);
        canvas.toBlob(function (blob) {
          var file = new File([blob], 'captured-image.jpg', { type: 'image/jpeg' });
          var dt = new DataTransfer();
          dt.items.add(file);

          // Create a hidden input field for the image file
          var input = document.createElement('input');
          input.type = 'file';
          input.name = 'scan[image_url]';
          input.style.display = 'none';
          input.files = dt.files;
          document.getElementById('capture-form').appendChild(input);

          // Submit the form
          document.getElementById('capture-form').submit();
        }, 'image/jpeg');
      });
    </script>
  </body>
</html>

app/views/scans/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Extracted Text</title>
  </head>
  <body>
    <div class="container me-2 my-4">
      <h3><i class="fa-solid fa-magnifying-glass"></i> 読み取り結果 </h3>
      <div class="mx-2">
        <% if @extracted_text.present? %>
          <span>--------------------------------------------</span><br>
          <%= @extracted_text %>
          <p>--------------------------------------------</p>
        </div>
        <div data-refresh-list-target="result">
          <h3>＜含まれる添加物＞
            <% @matching_additives.each do |additive| %>
              <div class="card card-trip mb-3 od py-1 px-1" data-controller="enty-thinner" data-action="click->enty-thinner#dropdown">
                <div class="p-3">
                  <div class="overflow-container" data-enty-thinner-target="text">
                    <p class="pt-2 mb-0 fs-5">
                      <i class="fa-solid fa-caret-down"></i>
                      添加物名: <%= additive.display_name || additive.name %> </p>
                  </div>
                </div>
                <div class="justify-content-center p-3 d-none" data-enty-thinner-target="details">
                  <div class="justify-content-center p-3">
                    <% if additive.information.present? %>
                      <p class="pt-2 mb-2 fs-5"> 詳細: <%= additive.information %></p>
                    <% end %>
                    <% if additive.purpose.present? %>
                      <p class="pt-2 mb-0 fs-5">用途: <%= additive.purpose %></p>
                    <% end %>
                    <% if additive.url.present? %>
                      参考サイト: <a href="<%= additive.url %>" target="_blank"><%= additive.url %></a>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </h3>
          <h3>＜アレルギー＞</h3>
          <div class="icon-inline mx-3 mt-3 mb-2">
            <% @matching_allergens.map { |allergen| allergen.icon }.uniq.each do |icon| %>
              <%= image_tag icon, class: "icon-smaller" %>
            <% end %>
          <% else %>
            <p>No text found in the image.</p>
          <% end %>
        </div>
        <p class="mx-3 fst-italic">※読み取った写真から抽出していますが、実際と異なる場合がありますのでご注意ください</p>
        <a href="/scans/new" class="button">もう一度撮影 <i class="fa-solid fa-camera"></i></a>
        <a href="/additives" class="button">ホームに戻る <i class="fa-solid fa-house"></i></a>
      </div>
    </body>
  </html>